ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('bedroom',views.bedroom,name='bedroom'),
    path('livingroom',views.livingroom,name='livingroom'),
    path('diningroom',views.diningroom,name='diningroom'),
    path('bedding',views.bedding,name='bedding'),
    path('youth',views.youth,name='youth'),
    path('newarrival',views.newarrival,name='newarrival'),
    path('login',views.login,name='login'),
    path('signup',views.signup,name='signup'),
    path('logout',views.logout, name='logout'),
    path('about',views.about,name='about'),
    path('warranty', views.warranty, name='warranty'),
    path('shippingpolicy',views.shippingpolicy,name='shippingpolicy'),
    path('privacypolicy', views.privacypolicy, name='privacypolicy'),
    path('termsandpolicy', views.termsandpolicy, name='termsandpolicy'),
    path('tracking', views.tracking, name='tracking'),
    path('contact',views.contact,name='contact'),
    path('product/<int:id>',views.product,name='product'),
    path('cart_detail',views.cart_detail,name='cart_detail'),
    path('cart_add/<int:id>',views.cart_add,name='cart_add'),
    path('cart_remove/<int:id>',views.cart_remove,name='cart_remove'),
    path('checkout',views.checkout,name='checkout'),
    path('order',views.order, name='order'),
    path('generateinvoice/<int:id>/', views.GenerateInvoice.as_view(), name = 'generateinvoice'),
    path('orderview/<str:t_no>',views.orderview, name='orderview'),
    path('payment_process',views.payment_process, name='payment_process'),
    path('payment_done', views.payment_done, name='payment_done'),
    path('payment_cancelled',views.payment_cancelled, name= 'payment_cancelled'),
]

shop/models.py
from asyncio.windows_events import NULL
from email import message
import email
from email.policy import default
from enum import unique
from unicodedata import category, name
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.


class Category(models.Model):
    category = models.CharField(max_length=50, default="")

    def __str__(self):
        return self.category


class Product(models.Model):
    product_id = models.AutoField
    product_name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    price = models.FloatField(default=0)
    desc = models.TextField(default="Description Here")
    pub_date = models.DateField()
    image = models.ImageField(upload_to="shop/images", default="")

    def __str__(self):
        return self.product_name


class Order(models.Model):
    user=  models.ForeignKey(User,
                                  on_delete=models.CASCADE, null= True, unique=False)
    name = models.CharField(max_length=150, null= False, default='')
    email = models.EmailField(null= False)
    phone= models.CharField(max_length=12, null= False, default= 1)
    address = models.TextField( null= False)
    city = models.CharField(max_length=100 , null= False)
    state = models.CharField(max_length=100 , null= False, default="USA")
    country = models.CharField(max_length=100, null= False) 
    zip_code = models.CharField(max_length=6, null= False)  
    total_price= models.FloatField(null= False)
    payment_mode= models.CharField(max_length=50, null= False)
    payment_id= models.CharField(max_length=150, null= True)
    orderstatus=(
        ('Pending','Pending'),
        ('Out For Shipping','Out For Shipping'),
        ('Completed', 'Completed')
    )
    status= models.CharField(max_length=50, choices= orderstatus, default='Pending')
    message=models.TextField(null= True,default= "Thanks For Ordering with us. We will update the status soon")
    tracking_no= models.CharField(max_length=150, null= True)
    created_at= models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}-{}'.format(self.id, self.tracking_no)

    

class OrderItem(models.Model):
        order = models.ForeignKey(Order,
                                  on_delete=models.CASCADE)
        product = models.ForeignKey(Product,
                                 on_delete=models.CASCADE)
        price = models.FloatField(null= False)
        quantity = models.PositiveIntegerField(default=1)

        def __str__(self):
            return '{} {}'.format(self.order.id, self.order.tracking_no)

        def get_cost(self):
            return self.price * self.quantity
        
        
class ContactForm(models.Model):
    user=  models.ForeignKey(User,
                                  on_delete=models.CASCADE, null= True, unique=False)
    name= models.CharField(max_length=150, null= False, default='')
    phone= models.CharField(max_length=12, null= False, default= 1)
    email= models.EmailField(null= False, default= '')
    subject= models.CharField(max_length=50, null= False, default='')
    message= models.CharField(max_length=1000, null= False, default='')
    
    def __str__(self):
        return self.name
        

shop/forms.py
from turtle import color
from django import forms


PRODUCT_QUANTITY_CHOICES= [(i,str(i)) for i in range(1,21,1)]
class CartAddProductForm(forms.Form):
    quantity= forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override= forms.BooleanField(required= False, initial=False, widget=forms.HiddenInput)
    
    

shop/views.py
from multiprocessing import context
from os import remove
from django.views.generic import View
from unicodedata import category
from django.http import HttpResponse, JsonResponse
from .models import Product, Order, OrderItem, ContactForm
from .models import Category
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .cart import Cart
from .forms import CartAddProductForm
from django.views.decorators.http import require_POST
from django.conf import settings
from django.core.mail import send_mail, EmailMessage, EmailMultiAlternatives
import random
from django.db.models import Min, Max
from django.views.decorators.csrf import csrf_exempt
from io import BytesIO
from django.template.loader import get_template
from xhtml2pdf import pisa
import os

def home(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})
        
    #return render(request, 'home.html', {'cart': cart})
    if bedding:
        products = Product.objects.filter(category=4)
        return render(request, 'home.html', {'product': products, 'category': 4, 'cart': cart})


def bedroom(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})
    if bedroom: 
        products = Product.objects.filter(category=1)
        return render(request, 'bedroom.html', {'product': products, 'category': 1, 'cart': cart})
  
    
        


def livingroom(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})
    if livingroom:
        products = Product.objects.filter(category=2)
        return render(request, 'livingroom.html', {'product': products, 'category': 2, 'cart': cart})


def diningroom(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})
    if diningroom:
        products = Product.objects.filter(category=3)
        return render(request, 'diningroom.html', {'product': products, 'category': 3, 'cart': cart})


def bedding(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})
    if bedding:
        products = Product.objects.filter(category=4)
        return render(request, 'bedding.html', {'product': products, 'category': 4, 'cart': cart})


def youth(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})
    if youth:
        products = Product.objects.filter(category=5)
        return render(request, 'youth.html', {'product': products, 'category': 5, 'cart': cart})


def newarrival(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})
    products = Product.objects.all().order_by('-pub_date')
    return render(request, 'newarrival.html', {'product': products, 'cart': cart})


def login(request):
    return render(request, 'login.html')


def signup(request):

    if request.method == "POST":
        # Get the Post Parameter
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, "Username Already Taken")
                return redirect("signup")
            elif User.objects.filter(email=email).exists():
                messages.info(request, "Email Already Taken")
                return redirect("signup")
            else:
                # Create User
                user = User.objects.create_user(username=username,
                                                first_name=first_name, last_name=last_name, email=email, password=password1)
                user.save()
                
                subject = 'Welcome to Dream Decor'
                message = f'Hi {user.username}, thank you for registering in Dream Decor.'
                email_from = settings.EMAIL_HOST_USER
                recipient_list = [user.email, ]
                send_mail( subject, message, email_from, recipient_list )
                return redirect("login")

        else:
            messages.info(request, "Password not matching")
            return redirect("signup")

    else:
        return render(request, 'signup.html')
    


def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            request.session['user_id'] = user.id
            request.session['username'] = user.username
            return redirect("home")
        else:
            messages.info(request, "Invalid Credentials")
            return redirect("login")

    else:
        return render(request, "login.html")


def logout(request):
    auth.logout(request)
    return redirect("home")


def product(request, id):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})
    products = Product.objects.filter(id=id)
    cart_product_form = CartAddProductForm()
    return render(request, 'product.html', {'product': products, 'cart_product_form': cart_product_form, 'cart': cart})


@require_POST
def cart_add(request, id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart_detail')


def cart_remove(request, id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=id)
    cart.remove(product)
    return redirect('cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})
    return render(request, 'cart/detail.html', {'cart': cart})


@login_required(login_url='login')
def checkout(request):
    cart = Cart(request)
    if request.method == 'POST':
        neworder = Order()
        current_user = request.user
        neworder.user = User.objects.get(id=current_user.id)
        neworder.name = request.POST.get('name')
        neworder.address = request.POST.get('address')
        neworder.email = request.POST.get('email')
        neworder.phone = request.POST.get('phone')
        neworder.city = request.POST.get('city')
        neworder.state = request.POST.get('state')
        neworder.country = request.POST.get('country')
        neworder.zip_code = request.POST.get('zip_code')

        neworder.payment_mode = request.POST.get('payment_mode')

        cart = Cart(request)
        cart.get_total_price=0
        for item in cart:
            cart.get_total_price = cart.get_total_price + item['price']*item['quantity']

            neworder.total_price = cart.get_total_price
            trackingno = 'DreamDecor_' + str(random.randint(1111111, 9999999))
            while Order.objects.filter(tracking_no=trackingno) is None:
                trackingno = 'DreamDecor_' + \
                    str(random.randint(1111111, 9999999))

            neworder.tracking_no = trackingno
            neworder.save()
            neworderitems = Cart(request)
            for item in neworderitems:
                OrderItem.objects.create(order=neworder,
                                         product=item['product'],
                                         price=item['total_price'],
                                         quantity=item['quantity'])

            cart.clear()
            template = get_template('cart/invoice.html')
            data = {
                        'order_id': str(neworder.id),
                        'user_email': neworder.email,
                        'date': str(neworder.created_at),
                        'name': neworder.name,
                        'order': neworder,
                        'amount': neworder.total_price,
                    }
            html  = template.render(data)
            result = BytesIO()
            pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)#, link_callback=fetch_resources)
            pdf = result.getvalue()
            filename = 'Invoice_' + data['order_id'] + '.pdf'

            mail_subject = 'Recent Order Details'
                    # message = render_to_string('firstapp/payment/emailinvoice.html', {
                    #     'user': order_db.user,
                    #     'order': order_db
                    # })
            context_dict = {
                        'user': neworder.user,
                        'order': neworder
                    }
            template = get_template('cart/email.html')
            message  = template.render(context_dict)
            to_email = neworder.email
                    # email = EmailMessage(

shop/templates/cart/detail.html
{% extends 'basic.html' %}

{% block title%}Shopping Cart{%endblock%}
{% block body%}
{% load static %}
<div class="container"><br>
    <h1 style="font-weight:200;">Shopping Cart</h1><br>
    <div class="table-responsive-lg">
        <table class="table  table-bordered border-dark table-hover">
            <thead>
                <tr>
                    <th scope="col">Serial no.</th>
                    <th scope="col">Image</th>
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Remove</th>
                    <th scope="col">Unit Price</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>
                        <a href="{{product.get_absolute_url}}">
                            <img src="{% if product.image %} {{product.image.url}}
                               {% else %}{% static "img/no_image.png" %}{% endif%} " style=" width:50px; height:50px;"
                                class="rounded">
                        </a>
                    </td>
                    <td>{{ product.product_name }}</td>
                    <td>
                        <form action="{% url "cart_add" product.id %}" method="post">
                            {% csrf_token %}
                            {{item.update_quantity_form.quantity}}
                            {{item.update_quantity_form.override}}
                            <input type="submit" value="add">
                        </form>
                    </td>
                    <td>
                        <form action=" {% url "cart_remove" product.id %}" method="post">
                            <input type="submit" value="Remove">
                            {% csrf_token %}

                        </form>
                    </td>
                    <td class="num">${{item.price}}</td>
                    <td class="num">${{item.total_price}}</td>
                </tr>
                {% endwith %}
                {% endfor %}
                <tr class="table-dark">
                    <td colspan="5"></td>
                    <td class="table-dark">Total Price</td>
                    <td class="num">${{cart.get_total_price}}</td>

                </tr>
            </tbody>

        </table>

        <p class="text-end">
            <a href="/newarrival" type="button" class="btn btn-outline-primary">Continue Shopping</a>
            <button data-bs-toggle="modal" data-bs-target="#exampleModal" type="button"
                class="btn btn-outline-primary">Check Out</button>
        </p>
        {% for message in messages %}
        <h3 class="alert alert-primary" role="alert">{{message}}</h3>
        {% endfor %}
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="color:white; background-color:black;">
                <h5 class="modal-title fs-5" id="exampleModalLabel">Check Out Form</h5>
                <hr>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" style="background-color:aquamarine;">
                <div class="m-2 p-3">
                    <form action="checkout" , method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="">Name</label>
                            <input type="text" name="name" required class="form-control" placeholder=""
                                aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label for="">Email</label>
                            <input type="email" name="email" required class="form-control" placeholder=""
                                aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label for="">Phone</label>
                            <input type="number" name="phone" required class="form-control" placeholder=""
                                aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label for="">Address</label>
                            <input type="text" name="address" required class="form-control" placeholder=""
                                aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label for="">City</label>
                            <input type="city" name="city" required class="form-control" placeholder=""
                                aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label for="">State</label>
                            <input type="city" name="state" required class="form-control" placeholder=""
                                aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label for="">Country</label>
                            <input type="city" name="country" required class="form-control" placeholder=""
                                aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label for="">Zip Code</label>
                            <input type="number" name="zip_code" required class="form-control" placeholder=""
                                aria-describedby="helpId">
                        </div>
                        <br>
                        <input type="hidden" value="Offline" name="payment_mode">
                        <button type="submit" class="btn btn-primary btn-lg col-12 mb-2 ">Pay Offline</button>
                        <div id="paypal-button-container"></div>
                        <script src="https://www.paypal.com/sdk/js?client-id=AY4UfSai_p2RCyo-olaiipTHRE93EuPvOUQto4Bf6pKE1KPtVjIE46VdoxXTzQT_HmhLzVCAE9uq71_P&currency=USD"></script>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    paypal.Buttons({
      // Sets up the transaction when a payment button is clicked
      createOrder: (data, actions) => {
        return actions.order.create({
          purchase_units: [{
            amount: {
              value: '{{cart.get_total_price}}' // Can also reference a variable or function
            }
          }]
        });
      },
      // Finalize the transaction after payer approval
      onApprove: (data, actions) => {
        return actions.order.capture().then(function(orderData) {
          // Successful capture! For dev/demo purposes:
          console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
          const transaction = orderData.purchase_units[0].payments.captures[0];
          alert(`Transaction ${transaction.status}: ${transaction.id}\n\nSee console for all available details`);
          // When ready to go live, remove the alert and show a success message within this page. For example:
          // const element = document.getElementById('paypal-button-container');
          // element.innerHTML = '<h3>Thank you for your payment!</h3>';
          // Or go to another URL:  actions.redirect('thank_you.html');
        });
      }
    }).render('#paypal-button-container');
  </script>
{% endblock %}

shop/templates/cart/email.html
<div style="background-color: rgb(228, 228, 228);">
    <div style="margin: 20px; background-color: #fff;">

Hi {{ user.name }},
Your order with order id: {{order.id}} has been placed successfully.

Your order consists of - 
{% for i in order.orderitem_set.all %}
Product:{{i.product}} Quantity:{{i.quantity}} Price:{{i.price}}
{% endfor %}
Total:{{order.total_price}}
<br><br>

Order will reach to you in 5-7 days.

We have attached the invoice for your order with this mail.

Thanks for trusting us and using our services!

Sincerely,
Dream Decor Team

    </div>
</div>

shop/templates/cart/invoice.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <title>Dream Decor</title>
<style>
  .clearfix:after {
  content: "";
  display: table;
  clear: both;
}

a {
  text-decoration: underline;
}

body {
  position: relative;
  margin: 0 auto; 
  color: #001028;
  background: #FFFFFF; 
  font-family: Arial, sans-serif; 
  font-size: 14px; 
  font-family: Arial;
}

header {
  padding: 10px 0;
  margin-bottom: 30px;
}

#logo {
  text-align: center;
  margin-bottom: 10px;
}

#logo img {
  width: 90px;
}

h1 {
  
  color: #5D6975;
  font-size: 2.4em;
  line-height: 1.4em;
  font-weight: normal;
  text-align: center;
  margin: 0 0 20px 0;
}

#project {
  float: left;
}

#project span {
  color: #5D6975;
  text-align: right;
  width: 52px;
  margin-right: 10px;
  display: inline-block;
  font-size: 14px;
}

#company {
  float: right;
  text-align: right;
}

#project div,
#company div {
  white-space: nowrap;        
}

table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  margin-bottom: 20px;
}



table th,
table td {
  text-align: center;
}

table th {
  
  
  color: #5D6975;
  border-bottom: 1px solid #C1CED9;
  white-space: nowrap;        
  font-weight: normal;
}

table .service,
table .desc {
  text-align: left;
}

table td {
 padding-top:5px;
 padding-bottom:5px;
  
}

table tr {
  border-bottom: 1px solid #C1CED9;
}

table td.service,
table td.desc {
  vertical-align: top;
}

table td.unit,
table td.qty,
table td.total {
  font-size: 1.2em;
}

table td.grand {
  border-top: 1px solid #5D6975;;
}

#notices .notice {
  color: #5D6975;
  font-size: 1.2em;
}

footer {
  color: #5D6975;
  width: 100%;
  height: 30px;
  position: absolute;
  bottom: 0;
  border-top: 1px solid #C1CED9;
  padding: 8px 0;
  text-align: center;
}


  </style>
</head>

<body>
  <header class="clearfix">
    <div id="logo" style="display:flex; justify-content:center; align-items:center;">
      {#<img src="static/firstapp/images/logo.png" class="brand-logo" width=60 height=60>#} <!--not working-->
      {#<img src="static/logo.png" class="brand-logo" height="200px">#} <!--not working-->
      {#<img src="D:\Mastering Django\firstproject\firstapp\logo.png" class="brand-logo" width=60 height=60>#}
      <h1 class="brand-name">Dream Decor</h1>
    </div>
    <h1>INVOICE</h1>
    <div id="company" class="clearfix">
      <div>Dream Decor</div>
      <div><a href="mailto:company@example.com">company@example.com</a></div>
      <div><a href="www.Dreamdecor.com:8000">www.Dreamdecor.com</a></div>
    </div>
    <div id="project">
      <div><span>CLIENT:</span> {{name}}</div>
      <div><span>EMAIL:</span> <a href="mailto:{{user_email}}">{{user_email}}</a></div>
      <div><span>DATE:</span> {{order.created_at}}</div>
      <div><span>INVOICE ID:</span> {{order_id}}</div>
      <div><span>PAYMENT MODE:</span> {{order.payment_mode}}</div>
    </div>
    <br>
    <br>
  </header>
    <div class="table-container" style="overflow-x:auto">
      <table class="table" style="width:100%">
          <thead>
              <tr>
                  <th scope="col">PRODUCT</th>
                  <th scope="col">QUANTITY</th>
                  <th scope="col">PRICE</th>
              </tr>
          </thead>
          <tbody>
              {% for i in order.orderitem_set.all %}
              <tr>
                  <td scope="row">{{i.product}}</td>
                  <td>{{i.quantity}}</td>
                  <td>{{i.price}}</td>
                  
              </tr>
              {% endfor %}
              <tr>
                  <td scope="row"></td>
                  <td>TOTAL: </td>
                  <td>{{order.total_price}}</td>
                  
              </tr>
          </tbody>
      </table>

    </div>
    <p style="text-align:right; font-size:12px;">*All values are in USD<p>
</body>

</html>

shop/templates/cart/order.html
{% extends 'basic.html' %}

{% block title%}Order{%endblock%}
{% block body%}
<div style="padding:50px;">
    <h1 style="font-weight:200;">My Orders</h1>
    <br><br>
    <div class="table-responsive-lg">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">S.No</th>
                    <th scope="col">Date</th>
                    <th scope="col">Price</th>
                    <th scope="col">Status</th>
                    <th scope="col">Tracking no</th>
                    <th scope="col">Views</th>
                    <th scope="col">Track order</th>
                    <th scope="col">Invoice</th>
                </tr>
            </thead>
            <tbody>
                {% for i in orders %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{i.created_at}}</td>
                    <td>${{i.total_price}}</td>
                    <td>{{i.status}}</td>
                    <td>{{i.tracking_no}}</td>
                    <td><a class="btn btn-primary" href="{% url 'orderview' i.tracking_no%}">
                            Views
                        </a></td>
                    <td>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                            data-bs-target="#exampleModal">
                            Track order
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Track Your Order</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <p><b>Message:</b> {{i.message}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td><a class="btn btn-primary" href="{% url 'generateinvoice' i.id%}">
                        Download
                    </a></td>
                </tr>
             
                {%endfor%}
            </tbody>
        </table>
    </div>

</div>

{% endblock %}